import type { APIRoute } from 'astro';
import latestRelease from '../data/release.json';

// Sparkle appcast — consumed by SPUUpdater inside the macOS app.
// Format: https://sparkle-project.org/documentation/publishing/
//
// SUPublicEDKey in Info.plist must match the EdDSA public key generated by
// `generate_keys` from Sparkle's bin directory. The <sparkle:edSignature>
// values below are placeholders — replace them with real signatures produced
// by `sign_update` after each release build.

export const GET: APIRoute = () => {
  const version = latestRelease.version;
  const releaseDate = latestRelease.releaseDate;
  const downloadUrl = `https://www.defaulttamer.app${latestRelease.downloadUrl}`;
  const releaseNotesUrl = `https://www.defaulttamer.app/release-notes`;
  const edSignature = latestRelease.edSignature;
  const size = latestRelease.size;

  const xml = `<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"
    xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"
    xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Default Tamer Updates</title>
    <link>https://www.defaulttamer.app/appcast.xml</link>
    <description>Most recent changes to Default Tamer</description>
    <language>en</language>
    <item>
      <title>Version ${version}</title>
      <sparkle:version>${version}</sparkle:version>
      <sparkle:shortVersionString>${version}</sparkle:shortVersionString>
      <pubDate>${new Date(releaseDate).toUTCString()}</pubDate>
      <sparkle:releaseNotesLink>${releaseNotesUrl}</sparkle:releaseNotesLink>
      <sparkle:minimumSystemVersion>13.0</sparkle:minimumSystemVersion>
      <enclosure
        url="${downloadUrl}"
        sparkle:edSignature="${edSignature}"
        length="${size}"
        type="application/octet-stream"
      />
    </item>
  </channel>
</rss>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/rss+xml; charset=utf-8',
    },
  });
};
